"""Auto-generated conformance deliverables (build prompt §7).

Produces:
  * a per-standard conformance SCORECARD,
  * a machine-readable gaps.json — each entry
    {standard, spec_section, endpoint, expected, observed, severity, scenario},
  * a human-readable GAP_REPORT.md.

Both files are written to `settings.report_dir` and also returned in-process so
the API / dashboard can serve them without touching disk.
"""
from __future__ import annotations

import json
import os
from typing import Any, Dict, List, Optional

from app.config import Settings
from app.db import Database
from app.modules import metrics


async def gather(db: Database, settings: Settings, *, run_id: Optional[str] = None,
                 discovery: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    fsum = await metrics.findings_summary(db, run_id)
    scen_rows = await metrics.scenario_results(db, run_id)
    overview = await metrics.overview(db, run_id)
    fills = await metrics.fill_breakdown(db, run_id)

    # gaps.json: every fail/warn finding + every GAP/FAIL scenario, in the §7 schema.
    gaps: List[Dict[str, Any]] = []
    for f in fsum["findings"]:
        if f["severity"] in ("fail", "warn"):
            gaps.append({
                "standard": f["standard"], "spec_section": f["spec_section"],
                "endpoint": f.get("endpoint", ""), "expected": f["expected"],
                "observed": f["observed"], "severity": f["severity"],
                "scenario": f.get("scenario", ""), "check": f.get("check", ""),
            })
    for s in scen_rows:
        if s["verdict"] in ("GAP", "FAIL"):
            gaps.append({
                "standard": "Scenario", "spec_section": f"§6 / {s['scenario']}",
                "endpoint": "", "expected": s["expected"], "observed": s["actual"],
                "severity": "fail" if s["verdict"] == "FAIL" else "warn",
                "scenario": s["scenario"], "check": s["title"],
            })

    return {
        "scorecard": fsum["scorecard"], "findings": fsum["findings"], "gaps": gaps,
        "scenarios": scen_rows, "overview": overview, "fill_breakdown": fills,
        "discovery": discovery or {},
    }


def render_markdown(data: Dict[str, Any], settings: Settings) -> str:
    sc = data["scorecard"]
    ov = sc.get("overall", {})
    lines: List[str] = []
    lines.append("# Voise Ad Sim — Conformance GAP Report")
    lines.append("")
    lines.append(f"Target ad server: `{settings.ad_server_url}`")
    lines.append("")
    lines.append(f"**Overall:** {ov.get('grade')} — {ov.get('checks', 0)} checks "
                 f"(pass {ov.get('pass', 0)}, fail {ov.get('fail', 0)}, warn {ov.get('warn', 0)}, "
                 f"info {ov.get('info', 0)})")
    fb = data.get("fill_breakdown", {})
    if fb.get("total"):
        lines.append("")
        lines.append(f"**Fill:** real {fb.get('real', 0)} ({fb.get('real_fill_rate', 0):.0%}), "
                     f"filler {fb.get('filler', 0)} ({fb.get('filler_rate', 0):.0%}), "
                     f"no-fill {fb.get('no_fill', 0)}, error {fb.get('error', 0)}")
    lines.append("")

    lines.append("## Conformance scorecard (per standard)")
    lines.append("")
    lines.append("| Standard | Grade | Pass | Fail | Warn | Info |")
    lines.append("|---|---|---:|---:|---:|---:|")
    for s in sc.get("standards", []):
        lines.append(f"| {s['standard']} | {s['grade']} | {s['pass']} | {s['fail']} | "
                     f"{s['warn']} | {s['info']} |")
    lines.append("")

    lines.append("## Scenario results (S1–S15)")
    lines.append("")
    lines.append("| Scenario | Verdict | Title | Observed |")
    lines.append("|---|---|---|---|")
    for s in data.get("scenarios", []):
        actual = (s.get("actual") or "").replace("|", "\\|")[:160]
        lines.append(f"| {s['scenario']} | {s['verdict']} | {s['title']} | {actual} |")
    lines.append("")

    lines.append("## Gaps (failures & warnings)")
    lines.append("")
    if not data["gaps"]:
        lines.append("_No gaps recorded for this scope._")
    else:
        lines.append("| Severity | Standard | Spec | Expected | Observed |")
        lines.append("|---|---|---|---|---|")
        for g in data["gaps"][:300]:
            exp = (g["expected"] or "").replace("|", "\\|")[:90]
            obs = (g["observed"] or "").replace("|", "\\|")[:140]
            lines.append(f"| {g['severity']} | {g['standard']} | {g['spec_section']} | {exp} | {obs} |")
    lines.append("")
    lines.append("> Generated by Voise Ad Sim. A GAP/fail/warn means the SUT deviates from the IAB "
                 "standard — not a simulator defect. Verdicts are never loosened to match SUT behaviour.")
    return "\n".join(lines)


async def write_report(db: Database, settings: Settings, *, run_id: Optional[str] = None,
                       discovery: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
    data = await gather(db, settings, run_id=run_id, discovery=discovery)
    md = render_markdown(data, settings)
    written: Dict[str, str] = {}
    try:
        os.makedirs(settings.report_dir, exist_ok=True)
        md_path = os.path.join(settings.report_dir, "GAP_REPORT.md")
        json_path = os.path.join(settings.report_dir, "gaps.json")
        with open(md_path, "w", encoding="utf-8") as fh:
            fh.write(md)
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump({"scorecard": data["scorecard"], "gaps": data["gaps"],
                       "scenarios": data["scenarios"]}, fh, indent=2)
        written = {"markdown": md_path, "gaps_json": json_path}
    except OSError:
        written = {"error": "could not write report files (read-only fs?)"}
    return {"markdown": md, "gaps": data["gaps"], "scorecard": data["scorecard"],
            "scenarios": data["scenarios"], "written": written}
